M48
; DRILL file KiCad 10.0.4 date 2026-08-12T10:30:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-12T10:30:07+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T2
X10.5Y17.0
T3
X5.0Y94.0
X5.0Y5.0
X124.0Y94.0
X124.0Y5.0
T1
G00X6.1Y16.75
M15
G01X6.1Y17.25
M16
G05
M30
